### ISSUE TITLE
[NewFunction] - Джойстик

### ISSUE THREAD

**Issue by mf-code** [alexeyIvankov/princessGames#2]
Разработать демонстрационный модуль, который состоит из одной сцены, которая содержит:
- сам джойстик
- демо-объект, положение которого меняется согласно действиям пользователя с джойстиком
- земля по которой происходит перемещение объекта

При разработке можно ориентироваться на работу джойстика в мобильном приложении Lineage2

**Comment by Manchiken** [comment]
done
